- name: deploying production code
  hosts: localhost
  tasks:
  - name: installing pip3 packages
    pip:
      executable: /usr/bin/pip3
      requirements: /home/vagrant/django/requirements.txt
  - name: making /app directory
    file:
      path: /app
      state: directory
  - name: making /static directory
    file:
      path: /static
      state: directory
  - name: deploying to /app
    file:
      src: /home/vagrant/django
      dest: /app/django
      state: link
  - name: deploying uwsgi service 
    file:
      src: /app/django/etc/uwsgi.service
      dest: /etc/systemd/system/uwsgi.service
      state: link
  - name: deploy nginx server
    copy:
      src: /app/django/etc/nginx
      dest: /etc/nginx/sites-available/default
  - name: migrate databases
    shell:
      cmd: DJANGO_SETTINGS_MODULE=project.settings.prod python3 manage.py migrate
      chdir: /app/django/
  - name: collect statics
    shell:
      cmd: DJANGO_SETTINGS_MODULE=project.settings.prod python3 manage.py collectstatic --no-input
      chdir: /app/django/
  - name: start uwsgi service
    systemd:
      state: started
      name: uwsgi.service
  - name: restart nginx
    systemd:
      state: restarted
      name: nginx