apiVersion: v1
kind: Secret
metadata:
  name: oidc
type: Opaque
data:
  CLIENT_ID: <Base64 Encoding of Client ID here>
  CLIENT_SECRET: <Base64 Encoding of Client Secret here>
  OKTA_DOMAIN: <Base64 Encoding of Your Okta Domain here>
